/**
 * Organisation Services
 * These are the services for the organisation site. These will be called by the frontend to provide the data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fr.prayuda@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.server.models

/**
 *
 * @param id
 * @param name
 * @param lead
 * @param description
 * @param employees
 */
data class Department(
        val id: kotlin.Long? = null,
        val name: kotlin.String? = null,
        val lead: kotlin.String? = null,
        val description: kotlin.String? = null,
        val employees: kotlin.Array<Employee>? = null
) {

}

