/**
 * Organisation Services
 * These are the services for the organisation site. These will be called by the frontend to provide the data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fr.prayuda@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.server.dao


/**
 *
 * @param code
 * @param type
 * @param message
 */
data class ApiResponse(
        val code: kotlin.Int? = null,
        val type: kotlin.String? = null,
        val message: kotlin.String? = null
) {

}

