/**
 * Organisation Services
 * These are the services for the organisation site. These will be called by the frontend to provide the data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fr.prayuda@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.server.dao

/**
 * DAO for Department
 * @param id id of the organisation department
 * @param name department name
 * @param lead lead of the organisation department
 * @param description short explanation of the department
 */
data class Department(
        override val id: Long,
        override val name: String,
        override val lead: String,
        override val description: String
) : Organigram