/**
 * Organisation Services
 * These are the services for the organisation site. These will be called by the frontend to provide the data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fr.prayuda@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.server.dao

/**
 * DAO for Employees
 * @param id employee unique number id
 * @param name employee full name
 * @param empid employee unique user name
 * @param email employee email
 * @param phone employee phone number
 * @param jobtitle short description about employee job title
 */
data class Employee(
        val id: Long,
        val name: String,
        val empid: String,
        val email: String,
        val phone: String,
        val jobtitle: String
)